version: '3'

services:
  shopDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    ports:
      - 3306:3306
    volumes:
      - shopData:/var/lib/mysql
    networks:
      - shopNetwork
  shopDBinit:
    image: shop_db_init
    environment:
      - DATABASE_ADDRESS=shopDB
    depends_on:
      shopDB:
        condition: service_healthy
    networks:
      - shopNetwork
  owner:
    image: owner
    environment:
      - DATABASE_ADDRESS=shopDB
    depends_on:
      - shopDBinit
    ports:
      - 5001:5001
    networks:
      - shopNetwork
  customer:
    image: customer
    environment:
      - DATABASE_ADDRESS=shopDB
    depends_on:
      - shopDBinit
    ports:
      - 5002:5002
    networks:
      - shopNetwork
  courier:
    image: courier
    environment:
      - DATABASE_ADDRESS=shopDB
    depends_on:
      - shopDBinit
    ports:
      - 5003:5003
    networks:
      - shopNetwork
  adminerShop:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - shopNetwork


volumes:
  shopData:

networks:
  shopNetwork: